# Generated by Django 2.2.7 on 2019-12-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mob_num', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
